# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Aaron Wubshet/Desktop/FinalProjectContainer/FinalProject/FinalProject.srcs/sources_1/ip/bram_fft_output_buffer/bram_fft_output_buffer.xci
# IP: The module: 'bram_fft_output_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Aaron Wubshet/Desktop/FinalProjectContainer/FinalProject/FinalProject.srcs/sources_1/ip/bram_fft_output_buffer/bram_fft_output_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_fft_output_buffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/Aaron Wubshet/Desktop/FinalProjectContainer/FinalProject/FinalProject.srcs/sources_1/ip/bram_fft_output_buffer/bram_fft_output_buffer.xci
# IP: The module: 'bram_fft_output_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Aaron Wubshet/Desktop/FinalProjectContainer/FinalProject/FinalProject.srcs/sources_1/ip/bram_fft_output_buffer/bram_fft_output_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_fft_output_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
