# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Aaron Wubshet/Desktop/Nexys4FFTDemo-master/src/bd/fft_mag/ip/fft_mag_mult_gen_1_0/fft_mag_mult_gen_1_0.xci
# IP: The module: 'fft_mag_mult_gen_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Aaron Wubshet/Desktop/Nexys4FFTDemo-master/src/bd/fft_mag/ip/fft_mag_mult_gen_1_0/fft_mag_mult_gen_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_mag_mult_gen_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/Aaron Wubshet/Desktop/Nexys4FFTDemo-master/src/bd/fft_mag/ip/fft_mag_mult_gen_1_0/fft_mag_mult_gen_1_0.xci
# IP: The module: 'fft_mag_mult_gen_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Aaron Wubshet/Desktop/Nexys4FFTDemo-master/src/bd/fft_mag/ip/fft_mag_mult_gen_1_0/fft_mag_mult_gen_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_mag_mult_gen_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
