# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Common/Constraints_Master.xdc

# IP: ip/clk_manager/clk_manager.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_manager || ORIG_REF_NAME==clk_manager}]

# IP: ip/JW_BRAM_COLOR/JW_BRAM_COLOR.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==JW_BRAM_COLOR || ORIG_REF_NAME==JW_BRAM_COLOR}]

# XDC: ip/clk_manager/clk_manager_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_manager || ORIG_REF_NAME==clk_manager}] {/inst }]/inst ]]

# XDC: ip/clk_manager/clk_manager.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_manager || ORIG_REF_NAME==clk_manager}] {/inst }]/inst ]]

# XDC: ip/clk_manager/clk_manager_ooc.xdc

# XDC: ip/JW_BRAM_COLOR/JW_BRAM_COLOR_ooc.xdc
