# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Aaron Wubshet/Desktop/new_folder/Final_Project/Final_Project.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Aaron Wubshet/Desktop/new_folder/Final_Project/Final_Project.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip -quiet {{c:/Users/Aaron Wubshet/Desktop/new_folder/Final_Project/Final_Project.srcs/sources_1/ip/clk_manager/clk_manager.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Aaron Wubshet/Desktop/new_folder/Final_Project/Final_Project.srcs/sources_1/ip/clk_manager/clk_manager_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Aaron Wubshet/Desktop/new_folder/Final_Project/Final_Project.srcs/sources_1/ip/clk_manager/clk_manager.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Aaron Wubshet/Desktop/new_folder/Final_Project/Final_Project.srcs/sources_1/ip/clk_manager/clk_manager_ooc.xdc}}]
set_property is_locked true [get_files {{c:/Users/Aaron Wubshet/Desktop/new_folder/Final_Project/Final_Project.srcs/sources_1/ip/clk_manager/clk_manager.xci}}]

read_ip -quiet {{c:/Users/Aaron Wubshet/Desktop/new_folder/Final_Project/Final_Project.srcs/sources_1/ip/JW_BRAM_COLOR/JW_BRAM_COLOR.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Aaron Wubshet/Desktop/new_folder/Final_Project/Final_Project.srcs/sources_1/ip/JW_BRAM_COLOR/JW_BRAM_COLOR_ooc.xdc}}]
set_property is_locked true [get_files {{c:/Users/Aaron Wubshet/Desktop/new_folder/Final_Project/Final_Project.srcs/sources_1/ip/JW_BRAM_COLOR/JW_BRAM_COLOR.xci}}]

read_verilog -library xil_defaultlib {
  {C:/Users/Aaron Wubshet/Desktop/new_folder/Final_Project/Final_Project.srcs/sources_1/imports/New folder/sd_color_bram.v}
  {C:/Users/Aaron Wubshet/Desktop/new_folder/Final_Project/Final_Project.srcs/sources_1/imports/New folder/color_contour.v}
  {C:/Users/Aaron Wubshet/Desktop/new_folder/Final_Project/Final_Project.srcs/sources_1/imports/New folder/debug.v}
  {C:/Users/Aaron Wubshet/Desktop/new_folder/Final_Project/Final_Project.srcs/sources_1/imports/6.111_Final_Project/Julian/Color_output.v}
  {C:/Users/Aaron Wubshet/Desktop/new_folder/Final_Project/Final_Project.srcs/sources_1/imports/6.111_Final_Project/Common/sd_controller.v}
  {C:/Users/Aaron Wubshet/Desktop/new_folder/Final_Project/Final_Project.srcs/sources_1/imports/6.111_Final_Project/Common/display_8hex.v}
  {C:/Users/Aaron Wubshet/Desktop/new_folder/Final_Project/Final_Project.srcs/sources_1/imports/6.111_Final_Project/Common/debounce.v}
  {C:/Users/Aaron Wubshet/Desktop/new_folder/Final_Project/Final_Project.srcs/sources_1/imports/Common/vga.v}
  {C:/Users/Aaron Wubshet/Desktop/new_folder/Final_Project/Final_Project.srcs/sources_1/imports/6.111_Final_Project/Common/final_project.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Aaron Wubshet/Desktop/new_folder/Final_Project/Final_Project.srcs/constrs_1/imports/Common/Constraints_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Aaron Wubshet/Desktop/new_folder/Final_Project/Final_Project.srcs/constrs_1/imports/Common/Constraints_Master.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top final_project -part xc7a100tcsg324-3


write_checkpoint -force -noxdef final_project.dcp

catch { report_utilization -file final_project_utilization_synth.rpt -pb final_project_utilization_synth.pb }
