# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files {{c:/Users/Aaron Wubshet/Desktop/6.111_Final_Project/Wings/Working Project/WingsFinalProject/decahedral.coe}}
add_files -quiet {{c:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/ip/div_gen_0/div_gen_0.dcp}}
set_property used_in_implementation false [get_files {{c:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/ip/div_gen_0/div_gen_0.dcp}}]
read_ip -quiet {{C:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/ip/filter_input_buffer/filter_input_buffer.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/ip/filter_input_buffer/filter_input_buffer_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/ip/filter_input_buffer/filter_input_buffer.xci}}]

add_files {{C:/Users/Aaron Wubshet/Desktop/Nexys4FFTDemo-master/src/bd/fft_mag/fft_mag.bd}}
set_property used_in_implementation false [get_files -all {{c:/Users/Aaron Wubshet/Desktop/Nexys4FFTDemo-master/src/bd/fft_mag/ip/fft_mag_axis_register_slice_2_0/fft_mag_axis_register_slice_2_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Aaron Wubshet/Desktop/Nexys4FFTDemo-master/src/bd/fft_mag/ip/fft_mag_cordic_0_0/fft_mag_cordic_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Aaron Wubshet/Desktop/Nexys4FFTDemo-master/src/bd/fft_mag/ip/fft_mag_mult_gen_0_0/fft_mag_mult_gen_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Aaron Wubshet/Desktop/Nexys4FFTDemo-master/src/bd/fft_mag/ip/fft_mag_mult_gen_1_0/fft_mag_mult_gen_1_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Aaron Wubshet/Desktop/Nexys4FFTDemo-master/src/bd/fft_mag/ip/fft_mag_xfft_0_0/fft_mag_xfft_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{C:/Users/Aaron Wubshet/Desktop/Nexys4FFTDemo-master/src/bd/fft_mag/fft_mag_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Aaron Wubshet/Desktop/Nexys4FFTDemo-master/src/bd/fft_mag/fft_mag.bd}}]

read_ip -quiet {{C:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/ip/bram_fft_output_buffer/bram_fft_output_buffer.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/ip/bram_fft_output_buffer/bram_fft_output_buffer_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/ip/bram_fft_output_buffer/bram_fft_output_buffer.xci}}]

read_ip -quiet {{C:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/ip/clk_manager/clk_manager.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/ip/clk_manager/clk_manager_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/ip/clk_manager/clk_manager.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/ip/clk_manager/clk_manager_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/ip/clk_manager/clk_manager.xci}}]

read_ip -quiet {{c:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/ip/xy_bin/xy_bin.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/ip/xy_bin/xy_bin_ooc.xdc}}]
set_property is_locked true [get_files {{c:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/ip/xy_bin/xy_bin.xci}}]

read_verilog -library xil_defaultlib {
  {C:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/imports/Aaron/verilog/lpf_coeffs.v}
  {C:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/imports/Aaron/fir31.v}
  {C:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/imports/6.111_Final_Project/Aaron/verilog/filter_control.v}
  {C:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/imports/6.111_Final_Project/Aaron/verilog/audio_PWM.v}
  {C:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/imports/6.111_Final_Project/Aaron/verilog/audio_processing.v}
  {C:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/imports/New folder/sd_color_bram.v}
  {C:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/imports/New folder/color_contour.v}
  {C:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/imports/6.111_Final_Project/Common/sd_controller.v}
  {C:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/imports/6.111_Final_Project/Common/display_8hex.v}
  {C:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/imports/Julian/Color_output.v}
  {C:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/imports/6.111_Final_Project/Common/debounce.v}
  {C:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/sources_1/imports/6.111_Final_Project/Common/final_project.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/constrs_1/imports/Common/Constraints_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Aaron Wubshet/Desktop/Local Final Project/Final_Project/Final_Project.srcs/constrs_1/imports/Common/Constraints_Master.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top final_project -part xc7a100tcsg324-3


write_checkpoint -force -noxdef final_project.dcp

catch { report_utilization -file final_project_utilization_synth.rpt -pb final_project_utilization_synth.pb }
